version: "3.9"
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    networks:
      - internal
  postgres:
    image: postgres:13.2-alpine
    restart: always
    volumes:
      - "${POSTGRES_DATA}:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    networks:
      - internal
  engine:
    image: ghcr.io/donfaq/celbot:add-ci
    restart: always
    environment:
      - "REDIS_URL=redis://redis:6379/0"
      - "DROPBOX_TOKEN=${DROPBOX_TOKEN}"
      - "DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    entrypoint: [ "celery", "-A", "bot.engine.main", "worker", "-l", "INFO", "-c", "2" ]
    networks:
      - internal
  telegram-bot:
    image: ghcr.io/donfaq/celbot:add-ci
    restart: always
    environment:
      - "REDIS_URL=redis://redis:6379/0"
      - "DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      - "TELEGRAM_TOKEN=${TELEGRAM_TOKEN}"
    entrypoint: [ "python", "main.py", "telegram" ]
    networks:
      - internal
  discord-bot:
    image: ghcr.io/donfaq/celbot:add-ci
    restart: always
    environment:
      - "REDIS_URL=redis://redis:6379/0"
      - "DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      - "DISCORD_TOKEN=${DISCORD_TOKEN}"
    entrypoint: [ "python", "main.py", "discord" ]
    networks:
      - internal
  twitch-bot:
    image: ghcr.io/donfaq/celbot:add-ci
    restart: always
    environment:
      - "REDIS_URL=redis://redis:6379/0"
      - "DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      - "TWITCH_USERNAME=${TWITCH_USERNAME}"
      - "TWITCH_TOKEN=${TWITCH_TOKEN}"
      - "TWITCH_CHANNEL=${TWITCH_CHANNEL}"
    entrypoint: [ "python", "main.py", "twitch" ]
    networks:
      - internal
networks:
  internal: